# Youth session sign in  window is 08:00 - 09:30
# Youth session sign out window is 09:31 - 10:40
days: sunday
in-start-h: 8
in-start-m: 0
in-end-h: 9
in-end-m: 30
out-start-h: 9
out-start-m: 31
out-end-h: 10
out-end-m: 40