# this is a rough example, needs re-work
name: Upload to S3

on:
  push:
    branches:
      - main_non_existant_branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies (if needed)
      run: npm install

    - name: Inject config into index.html
      run: node app/inject-config.js

    - name: Upload to S3
      run: aws s3 cp app/index.html s3://${{ secrets.AWS_BUCKET }}/index.html --region ${{ secrets.AWS_REGION }} --acl public-read
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 